# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license="ARR"

[[mods]]
modId="decoca"
version="${file.jarVersion}"
displayName="Decoca"
authors="AlgorithmLX"
description='''
Decorations for kiskas
'''
[[dependencies.decoca]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.decoca]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
